### ISSUE TITLE
v1.5.0 checklist (Jellyfin 10.9)

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-sdk-kotlin#909]
Using this issue to list what needs to happen for the next SDK version. Version 1.5.0 will use the Jellyfin 10.9 API as base and drops support for Jellyfin 10.8.

## High priority

These items must be resolved before stable 1.5.0 release.

- [x] Release at least 1 preview version to gather feedback
- [x] Update to 10.9.0 stable OpenAPI specification
- [x] Rewrite SSL issues code
- [x] Update WebSockets documentation
- [ ] ~~Add v1.5 migration documentation~~

## Medium priority

These items are not necessary for release but would be nice to have.

- [x] Implement new coroutine based WebSocket API
- [ ] New ApiClient implementation interfaces
- [ ] Optimize generated RegEx patterns (#864)
